import { 
  WardRegion, 
  SensorNode, 
  ShelterPoint, 
  AlertNotification, 
  CommunityFieldReport, 
  AuditLogEntry, 
  GatewayMeshState,
  EvacuationCorridor
} from '../types';

export const INITIAL_WARDS: WardRegion[] = [
  {
    id: 'ward-rampur-4b',
    code: 'WR-04B',
    name: 'Rampur Basin 4B',
    district: 'Pauri Garhwal',
    basin: 'Khoh River Catchment',
    riskLevel: 'critical',
    riskScore: 84,
    rainfall1h: 62.4,
    rainfallDelta1h: 18.2,
    soilSaturationPct: 88,
    riverLevelM: 5.8,
    riverDangerMarkM: 4.2,
    datumBreachM: 1.6,
    householdsAtRisk: 1240,
    population: 4890,
    lat: 29.7468,
    lng: 78.5292,
    polygon: [
      [29.755, 78.515],
      [29.762, 78.535],
      [29.748, 78.548],
      [29.735, 78.530],
      [29.742, 78.518],
    ],
    sensorIds: ['sn-014', 'sn-015', 'sn-018', 'sn-022', 'sn-029'],
    weirDischargeRate: 1240,
    sluiceAperturePct: 65,
    lastAssessmentTime: '16:42:15 IST',
    statusSummary: 'Flash flood cresting with severe slope toe erosion along Khoh River bend. Immediate corridor evacuation active.',
  },
  {
    id: 'ward-bhelupur',
    code: 'WR-02A',
    name: 'Bhelupur Ridge',
    district: 'Pauri Garhwal',
    basin: 'Khoh Tributary',
    riskLevel: 'warning',
    riskScore: 68,
    rainfall1h: 46.8,
    rainfallDelta1h: 8.4,
    soilSaturationPct: 76,
    riverLevelM: 3.9,
    riverDangerMarkM: 4.0,
    datumBreachM: -0.1,
    householdsAtRisk: 620,
    population: 2310,
    lat: 29.7612,
    lng: 78.5420,
    polygon: [
      [29.765, 78.532],
      [29.775, 78.550],
      [29.760, 78.560],
      [29.750, 78.542],
    ],
    sensorIds: ['sn-031', 'sn-032'],
    weirDischargeRate: 680,
    sluiceAperturePct: 40,
    lastAssessmentTime: '16:41:00 IST',
    statusSummary: 'CatBoost susceptibility elevated due to 7-day antecedent precipitation. Watch for debris sliding near Sector 2 culvert.',
  },
  {
    id: 'ward-kotdwar-main',
    code: 'WR-01M',
    name: 'Kotdwar Market Lowlands',
    district: 'Pauri Garhwal',
    basin: 'Khoh Mainstem',
    riskLevel: 'advisory',
    riskScore: 48,
    rainfall1h: 31.0,
    rainfallDelta1h: 2.1,
    soilSaturationPct: 62,
    riverLevelM: 3.2,
    riverDangerMarkM: 4.2,
    datumBreachM: -1.0,
    householdsAtRisk: 340,
    population: 8900,
    lat: 29.7420,
    lng: 78.5140,
    polygon: [
      [29.748, 78.502],
      [29.754, 78.520],
      [29.738, 78.528],
      [29.732, 78.508],
    ],
    sensorIds: ['sn-035'],
    weirDischargeRate: 850,
    sluiceAperturePct: 50,
    lastAssessmentTime: '16:38:40 IST',
    statusSummary: 'Runoff accumulating along low-lying bazaar storm drains. Drainage pumps operational.',
  },
  {
    id: 'ward-srinagar-gorge',
    code: 'WR-08G',
    name: 'Srinagar Gorge East',
    district: 'Pauri Garhwal',
    basin: 'Alaknanda Gorge',
    riskLevel: 'safe',
    riskScore: 22,
    rainfall1h: 12.5,
    rainfallDelta1h: -1.4,
    soilSaturationPct: 44,
    riverLevelM: 2.1,
    riverDangerMarkM: 6.5,
    datumBreachM: -4.4,
    householdsAtRisk: 0,
    population: 3420,
    lat: 29.7820,
    lng: 78.5800,
    polygon: [
      [29.790, 78.565],
      [29.800, 78.590],
      [29.778, 78.598],
      [29.770, 78.575],
    ],
    sensorIds: ['sn-040'],
    weirDischargeRate: 410,
    sluiceAperturePct: 20,
    lastAssessmentTime: '16:35:00 IST',
    statusSummary: 'Nominal discharge. Bedrock gorge stable with low soil saturation.',
  },
  {
    id: 'ward-devprayag-south',
    code: 'WR-05S',
    name: 'Devprayag Confluence South',
    district: 'Tehri Garhwal',
    basin: 'Bhagirathi-Alaknanda',
    riskLevel: 'warning',
    riskScore: 71,
    rainfall1h: 49.0,
    rainfallDelta1h: 12.0,
    soilSaturationPct: 79,
    riverLevelM: 7.2,
    riverDangerMarkM: 7.5,
    datumBreachM: -0.3,
    householdsAtRisk: 480,
    population: 3100,
    lat: 29.7150,
    lng: 78.4900,
    polygon: [
      [29.725, 78.475],
      [29.730, 78.505],
      [29.705, 78.512],
      [29.698, 78.485],
    ],
    sensorIds: ['sn-044'],
    weirDischargeRate: 980,
    sluiceAperturePct: 55,
    lastAssessmentTime: '16:40:10 IST',
    statusSummary: 'Confluence backwater effect creating rapid surge at Southern river wall.',
  },
  {
    id: 'ward-chamoli-ridge',
    code: 'WR-11C',
    name: 'Chamoli Upper Escarpment',
    district: 'Chamoli',
    basin: 'Dhauliganga',
    riskLevel: 'critical',
    riskScore: 89,
    rainfall1h: 74.2,
    rainfallDelta1h: 22.0,
    soilSaturationPct: 93,
    riverLevelM: 4.8,
    riverDangerMarkM: 3.5,
    datumBreachM: 1.3,
    householdsAtRisk: 890,
    population: 1980,
    lat: 29.8050,
    lng: 78.6100,
    polygon: [
      [29.815, 78.595],
      [29.825, 78.625],
      [29.795, 78.630],
      [29.790, 78.605],
    ],
    sensorIds: ['sn-045'],
    weirDischargeRate: 1420,
    sluiceAperturePct: 80,
    lastAssessmentTime: '16:43:00 IST',
    statusSummary: '38° slope failure detected by acoustic emission node. Evacuation order in effect.',
  },
  {
    id: 'ward-pauri-crest',
    code: 'WR-03P',
    name: 'Pauri Hill Crest',
    district: 'Pauri Garhwal',
    basin: 'Nayyar Catchment',
    riskLevel: 'safe',
    riskScore: 19,
    rainfall1h: 8.2,
    rainfallDelta1h: -0.5,
    soilSaturationPct: 38,
    riverLevelM: 1.4,
    riverDangerMarkM: 3.5,
    datumBreachM: -2.1,
    householdsAtRisk: 0,
    population: 5400,
    lat: 29.7320,
    lng: 78.5520,
    polygon: [
      [29.740, 78.545],
      [29.745, 78.568],
      [29.722, 78.572],
      [29.718, 78.550],
    ],
    sensorIds: ['sn-048'],
    weirDischargeRate: 190,
    sluiceAperturePct: 15,
    lastAssessmentTime: '16:32:00 IST',
    statusSummary: 'Elevated plateau dry. Primary staging haven for lowland evacuees.',
  },
];

export const INITIAL_SENSORS: SensorNode[] = [
  {
    id: 'sn-014',
    code: 'SN-014',
    name: 'Kotdwar Ridge MPU-6050',
    type: 'mpu6050',
    wardId: 'ward-rampur-4b',
    locationName: 'Kotdwar Ridge Slope A (Node 22)',
    lat: 29.7482,
    lng: 78.5270,
    status: 'online',
    batteryVoltage: 4.18,
    batteryPct: 98,
    rssiDbm: -68,
    snrDb: 9.4,
    lastSeen: 'Live 50Hz',
    ipOrAddress: '192.168.1.75 / LoRA 868.1 MHz',
    firmware: 'ZD-ESP32-v3.8.4',
  },
  {
    id: 'sn-015',
    code: 'SN-015',
    name: 'Rampur Khoh Ultrasonic Weir',
    type: 'ultrasonic_weir',
    wardId: 'ward-rampur-4b',
    locationName: 'Rampur Weir #3 Flume',
    lat: 29.7455,
    lng: 78.5298,
    status: 'online',
    batteryVoltage: 4.05,
    batteryPct: 89,
    rssiDbm: -72,
    snrDb: 8.2,
    lastSeen: '12s ago',
    ipOrAddress: 'JSN-SR04T Node 15',
    firmware: 'ZD-WEIR-v2.1.0',
  },
  {
    id: 'sn-018',
    code: 'SN-018',
    name: 'Sector 4B Soil Moisture Array',
    type: 'soil_moisture',
    wardId: 'ward-rampur-4b',
    locationName: 'Basin Escarpment Subsurface 40cm',
    lat: 29.7470,
    lng: 78.5312,
    status: 'online',
    batteryVoltage: 3.92,
    batteryPct: 81,
    rssiDbm: -77,
    snrDb: 7.1,
    lastSeen: '4s ago',
    ipOrAddress: 'Chirp I2C 0x20',
    firmware: 'ZD-SOIL-v1.4.2',
  },
  {
    id: 'sn-022',
    code: 'SN-022',
    name: 'Kotdwar Ridge Secondary MPU',
    type: 'mpu6050',
    wardId: 'ward-rampur-4b',
    locationName: 'Kotdwar Ridge Benchmark B',
    lat: 29.7495,
    lng: 78.5260,
    status: 'online',
    batteryVoltage: 4.12,
    batteryPct: 94,
    rssiDbm: -69,
    snrDb: 9.1,
    lastSeen: 'Live 50Hz',
    ipOrAddress: 'I2C 0x68 / 400kHz',
    firmware: 'ZD-ESP32-v3.8.4',
  },
  {
    id: 'sn-029',
    code: 'SN-029',
    name: 'Rampur Sluice Gate Actuator',
    type: 'sluice_actuator',
    wardId: 'ward-rampur-4b',
    locationName: 'Rampur Dam Intake Tower',
    lat: 29.7448,
    lng: 78.5285,
    status: 'online',
    batteryVoltage: 12.8,
    batteryPct: 100,
    rssiDbm: -64,
    snrDb: 11.0,
    lastSeen: '1s ago',
    ipOrAddress: 'Modbus RS485 Gateway',
    firmware: 'ZD-ACTUATE-v4.0.1',
  },
  {
    id: 'sn-031',
    code: 'SN-031',
    name: 'Bhelupur Tributary Gauge',
    type: 'ultrasonic_weir',
    wardId: 'ward-bhelupur',
    locationName: 'Bhelupur Nallah Bridge',
    lat: 29.7610,
    lng: 78.5410,
    status: 'online',
    batteryVoltage: 3.88,
    batteryPct: 78,
    rssiDbm: -82,
    snrDb: 6.4,
    lastSeen: '15s ago',
    ipOrAddress: 'LoRA Node 31',
    firmware: 'ZD-WEIR-v2.1.0',
  },
  {
    id: 'sn-032',
    code: 'SN-032',
    name: 'Bhelupur Ridge Inclinometer',
    type: 'mpu6050',
    wardId: 'ward-bhelupur',
    locationName: 'Bhelupur Cut-Slope #2',
    lat: 29.7635,
    lng: 78.5435,
    status: 'degraded',
    batteryVoltage: 3.52,
    batteryPct: 24,
    rssiDbm: -94,
    snrDb: 2.1,
    lastSeen: '2m ago',
    ipOrAddress: 'LoRA Node 32',
    firmware: 'ZD-ESP32-v3.8.0',
  },
  {
    id: 'sn-035',
    code: 'SN-035',
    name: 'Kotdwar Bazaar Weather Station',
    type: 'rain_gauge',
    wardId: 'ward-kotdwar-main',
    locationName: 'Tehsil Building Rooftop',
    lat: 29.7415,
    lng: 78.5135,
    status: 'online',
    batteryVoltage: 4.22,
    batteryPct: 99,
    rssiDbm: -61,
    snrDb: 12.4,
    lastSeen: '5s ago',
    ipOrAddress: 'Tipping Bucket 0.2mm',
    firmware: 'ZD-METEO-v2.2.0',
  },
  {
    id: 'sn-040',
    code: 'SN-040',
    name: 'Srinagar Flume Sensor',
    type: 'ultrasonic_weir',
    wardId: 'ward-srinagar-gorge',
    locationName: 'Gorge Hydrology Bench',
    lat: 29.7825,
    lng: 78.5795,
    status: 'offline',
    batteryVoltage: 2.90,
    batteryPct: 4,
    rssiDbm: -112,
    snrDb: -4.0,
    lastSeen: '4h ago',
    ipOrAddress: 'LoRA Node 40',
    firmware: 'ZD-WEIR-v2.0.4',
  },
  {
    id: 'sn-044',
    code: 'SN-044',
    name: 'Devprayag Acoustic Gauge',
    type: 'ultrasonic_weir',
    wardId: 'ward-devprayag-south',
    locationName: 'Sangam Retaining Wall',
    lat: 29.7145,
    lng: 78.4895,
    status: 'online',
    batteryVoltage: 4.02,
    batteryPct: 86,
    rssiDbm: -74,
    snrDb: 7.9,
    lastSeen: '9s ago',
    ipOrAddress: 'LoRA Node 44',
    firmware: 'ZD-WEIR-v2.1.0',
  },
  {
    id: 'sn-045',
    code: 'SN-045',
    name: 'Chamoli Escarpment Geophone',
    type: 'mpu6050',
    wardId: 'ward-chamoli-ridge',
    locationName: 'Shear Zone Borehole C-1',
    lat: 29.8040,
    lng: 78.6090,
    status: 'online',
    batteryVoltage: 4.14,
    batteryPct: 96,
    rssiDbm: -70,
    snrDb: 8.8,
    lastSeen: 'Live 50Hz',
    ipOrAddress: 'LoRA Node 45',
    firmware: 'ZD-ESP32-v3.8.4',
  },
  {
    id: 'sn-048',
    code: 'SN-048',
    name: 'Pauri Hilltop Repeater Node',
    type: 'rain_gauge',
    wardId: 'ward-pauri-crest',
    locationName: 'Forest Rest House Peak',
    lat: 29.7315,
    lng: 78.5515,
    status: 'online',
    batteryVoltage: 4.25,
    batteryPct: 100,
    rssiDbm: -58,
    snrDb: 13.5,
    lastSeen: '2s ago',
    ipOrAddress: 'LoRA Gateway Hub',
    firmware: 'ZD-GATEWAY-v5.0.1',
  },
];

export const INITIAL_SHELTERS: ShelterPoint[] = [
  {
    id: 'sh-rampur-school',
    code: 'SH-01',
    name: 'Govt. Primary School, Rampur',
    wardId: 'ward-rampur-4b',
    wardName: 'Rampur Basin 4B',
    lat: 29.7530,
    lng: 78.5340,
    capacity: 350,
    currentOccupancy: 120,
    elevationM: 890,
    bedrockStability: 'Stable bedrock',
    contactPhone: '+91-1382-224101',
    contactOfficer: 'Pradeep Rawat (Headmaster)',
    status: 'open',
    routeNotes: 'Approach via Ridge Road West. Avoid low river culvert #4.',
    suppliesDays: 5,
  },
  {
    id: 'sh-bhelupur-hall',
    code: 'SH-02',
    name: 'Community Hall, Bhelupur',
    wardId: 'ward-bhelupur',
    wardName: 'Bhelupur Ridge',
    lat: 29.7640,
    lng: 78.5460,
    capacity: 220,
    currentOccupancy: 45,
    elevationM: 940,
    bedrockStability: 'Stable bedrock',
    contactPhone: '+91-1382-225022',
    contactOfficer: 'Sarpanch Vimla Devi',
    status: 'open',
    routeNotes: 'Sector 4 bypass clear of runoff. Stable bedrock apron.',
    suppliesDays: 4,
  },
  {
    id: 'sh-panchayat-kotdwar',
    code: 'SH-03',
    name: 'Panchayat Bhawan, Kotdwar',
    wardId: 'ward-kotdwar-main',
    wardName: 'Kotdwar Market Lowlands',
    lat: 29.7390,
    lng: 78.5190,
    capacity: 450,
    currentOccupancy: 80,
    elevationM: 840,
    bedrockStability: 'Moderately weathered',
    contactPhone: '+91-1382-228399',
    contactOfficer: 'Sub-Divisional Magistrate Duty Office',
    status: 'open',
    routeNotes: 'Elevated plinth +3m above street storm mark. Backup diesel generator online.',
    suppliesDays: 7,
  },
  {
    id: 'sh-pauri-stadium',
    code: 'SH-04',
    name: 'Pauri Sports Complex Relief Camp',
    wardId: 'ward-pauri-crest',
    wardName: 'Pauri Hill Crest',
    lat: 29.7340,
    lng: 78.5560,
    capacity: 1200,
    currentOccupancy: 210,
    elevationM: 1120,
    bedrockStability: 'Stable bedrock',
    contactPhone: '+91-1382-229011',
    contactOfficer: 'SDRF 3rd Battalion Camp Command',
    status: 'open',
    routeNotes: 'Helipad operational. Water purification tanks full.',
    suppliesDays: 14,
  },
];

export const INITIAL_ALERTS: AlertNotification[] = [
  {
    id: 'alt-001',
    code: 'ALT-2026-0914',
    title: 'CRITICAL DIRECTIVE: Rampur Basin 4B Immediate Evacuation',
    titleHi: 'गंभीर निर्देश: रामपुर बेसिन 4B तुरंत खाली करें',
    body: 'Khoh River datum breach (+1.6m). CatBoost & LSTM hybrid risk engine threshold crossed (84%). Inhabitants must move immediately to Govt. Primary School Rampur. DO NOT cross the bridge.',
    bodyHi: 'खोह नदी खतरे के निशान से +1.6 मीटर ऊपर है। जोखिम स्तर 84%। सभी निवासी तुरंत राजकीय प्राथमिक विद्यालय रामपुर जाएं। नदी का पुल पार न करें।',
    severity: 'critical',
    regionId: 'ward-rampur-4b',
    regionName: 'Rampur Basin 4B',
    channels: ['push', 'sms', 'ble_mesh'],
    timestamp: '16:38:00 IST',
    status: 'active',
    deliveryStats: {
      targetNodes: 1240,
      deliveredNodes: 1198,
      avgLatencySec: 2.1,
    },
    author: 'Control Room Officer M. Joshi',
    authorRole: 'district_officer',
    directiveType: 'EVACUATION',
  },
  {
    id: 'alt-002',
    code: 'ALT-2026-0912',
    title: 'WARNING: Bhelupur Ridge Slope Saturation Advisory',
    titleHi: 'चेतावनी: भेलुपुर रिज ढलान संतृप्ति चेतावनी',
    body: '76% soil saturation with 46.8 mm/h rainfall. Debris flow watch in effect along Sector 2 culvert. Prepare staged shelters.',
    bodyHi: '76% मिट्टी संतृप्ति और 46.8 मिमी/घंटा बारिश। सेक्टर 2 कल्वर्ट के पास मलबा गिरने का खतरा। आश्रय स्थल तैयार रखें।',
    severity: 'warning',
    regionId: 'ward-bhelupur',
    regionName: 'Bhelupur Ridge',
    channels: ['push', 'sms'],
    timestamp: '16:15:00 IST',
    status: 'active',
    deliveryStats: {
      targetNodes: 620,
      deliveredNodes: 605,
      avgLatencySec: 1.8,
    },
    author: 'Autonomous AI Risk Engine',
    authorRole: 'super_admin',
    directiveType: 'STANDBY',
  },
];

export const INITIAL_REPORTS: CommunityFieldReport[] = [
  {
    id: 'rep-101',
    code: 'RPT-8821',
    category: 'slope_movement',
    description: 'Tension crack approx 12m length along road embankment 200m north of Rampur weir. Water bubbling through gravel.',
    wardId: 'ward-rampur-4b',
    wardName: 'Rampur Basin 4B',
    lat: 29.7475,
    lng: 78.5305,
    status: 'urgent',
    urgency: 'critical',
    timestamp: '16:22:10 IST',
    reporterName: 'Sunil Negi (PWD Guard)',
    reporterContact: '+91-98765-43210',
    verifiedBy: 'SDRF Patrol Alpha',
    verificationNotes: 'Verified on-site. Embankment slumping detected with 4cm displacement.',
  },
  {
    id: 'rep-102',
    code: 'RPT-8819',
    category: 'culvert_blockage',
    description: 'Fallen deodar pine tree and boulder blocking Sector 2 road drain. Water overflowing onto foot corridor.',
    wardId: 'ward-bhelupur',
    wardName: 'Bhelupur Ridge',
    lat: 29.7622,
    lng: 78.5430,
    status: 'verified',
    urgency: 'high',
    timestamp: '15:54:30 IST',
    reporterName: 'Anand Bisht',
    reporterContact: '+91-94120-11223',
    verifiedBy: 'Ward Rep Bhelupur',
    verificationNotes: 'Dispatched JCB from PWD Depot Kotdwar.',
  },
  {
    id: 'rep-103',
    code: 'RPT-8814',
    category: 'river_surge',
    description: 'Khoh river water level touching bottom girder of old suspension bridge. High timber debris.',
    wardId: 'ward-rampur-4b',
    wardName: 'Rampur Basin 4B',
    lat: 29.7460,
    lng: 78.5280,
    status: 'escalated',
    urgency: 'critical',
    timestamp: '15:30:00 IST',
    reporterName: 'Deepak Thapa',
    reporterContact: '+91-98971-88442',
    verifiedBy: 'District Officer',
    verificationNotes: 'Escalated to full bridge closure and police barricade.',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: 'aud-001',
    timestamp: '16:38:00 IST',
    actor: 'M. Joshi',
    role: 'district_officer',
    action: 'BROADCAST_ALERT',
    target: 'ward-rampur-4b',
    details: 'Broadcasted Critical Evacuation Directive ALT-2026-0914 via Push, SMS, and BLE Mesh to 1,240 nodes.',
    ipAddress: '10.14.2.45',
  },
  {
    id: 'aud-002',
    timestamp: '16:25:12 IST',
    actor: 'A. Negi',
    role: 'super_admin',
    action: 'SLUICE_OVERRIDE',
    target: 'sn-029',
    details: 'Opened Rampur Weir #3 gate from 40% to 65% aperture. Head pressure reduced to 142 kPa.',
    ipAddress: '10.14.2.11',
  },
  {
    id: 'aud-003',
    timestamp: '16:10:04 IST',
    actor: 'Autonomous Engine',
    role: 'super_admin',
    action: 'RISK_STATE_CHANGE',
    target: 'ward-rampur-4b',
    details: 'Escalated status from Warning to Critical based on combined CatBoost (82) + LSTM (86) blend.',
    ipAddress: '127.0.0.1 (Local Core)',
  },
  {
    id: 'aud-004',
    timestamp: '15:45:20 IST',
    actor: 'M. Joshi',
    role: 'district_officer',
    action: 'STAGE_SHELTER',
    target: 'sh-rampur-school',
    details: 'Staged Govt. Primary School Rampur with emergency supplies for 350 persons.',
    ipAddress: '10.14.2.45',
  },
];

export const INITIAL_GATEWAY_MESH: GatewayMeshState = {
  loraFrequencyMhz: 868.1,
  pdrPct: 99.4,
  packetCount: 184209,
  activeMeshNodes: 9,
  totalMeshNodes: 12,
  rangeKm: 12.4,
  cellGridActive: true,
  nodes: [
    { id: 'hub', label: 'HUB Central Base Station', role: 'gateway', lat: 29.7420, lng: 78.5140, distanceKm: 0.0, batteryPct: 100, lastPingMs: 14, hopCount: 0 },
    { id: 'r1', label: 'R1 Ridge Watchtower Repeater', role: 'repeater', lat: 29.7470, lng: 78.5240, distanceKm: 1.2, batteryPct: 98, lastPingMs: 42, hopCount: 1, parent: 'hub' },
    { id: 'r2', label: 'R2 Panchayat Office Node', role: 'repeater', lat: 29.7510, lng: 78.5310, distanceKm: 2.1, batteryPct: 92, lastPingMs: 68, hopCount: 2, parent: 'r1' },
    { id: 'r3', label: 'R3 Weir Guard Relay', role: 'repeater', lat: 29.7450, lng: 78.5290, distanceKm: 1.8, batteryPct: 88, lastPingMs: 58, hopCount: 2, parent: 'r1' },
    { id: 'rx1', label: 'RX Hilltop Resident Cluster A', role: 'endpoint', lat: 29.7540, lng: 78.5360, distanceKm: 2.8, batteryPct: 84, lastPingMs: 110, hopCount: 3, parent: 'r2' },
    { id: 'rx2', label: 'RX Kotdwar Valley Outpost', role: 'endpoint', lat: 29.7380, lng: 78.5220, distanceKm: 1.5, batteryPct: 76, lastPingMs: 82, hopCount: 2, parent: 'hub' },
  ],
};

export const INITIAL_EVACUATION_ROUTES: EvacuationCorridor[] = [
  {
    id: 'corridor-rampur-primary',
    code: 'COR-04B-A',
    originWardId: 'ward-rampur-4b',
    destinationShelterId: 'sh-rampur-school',
    shelterName: 'Govt. Primary School, Rampur',
    distanceKm: 1.8,
    walkTimeMinutes: 24,
    hazardAvoidanceNotes: 'Traverses upper western bedrock ridge. Completely bypasses submerged Khoh bridge and 36° toe escarpment.',
    elevationGainM: 42,
    clearanceStatus: 'Clear',
    lastChecked: '16:30 IST',
    waypoints: [
      [29.7468, 78.5292],
      [29.7485, 78.5310],
      [29.7505, 78.5325],
      [29.7530, 78.5340],
    ],
  },
  {
    id: 'corridor-bhelupur-primary',
    code: 'COR-02A-A',
    originWardId: 'ward-bhelupur',
    destinationShelterId: 'sh-bhelupur-hall',
    shelterName: 'Community Hall, Bhelupur',
    distanceKm: 2.2,
    walkTimeMinutes: 31,
    hazardAvoidanceNotes: 'Sector 4 ring road. Debris diversion berm installed at waypoint 2.',
    elevationGainM: 58,
    clearanceStatus: 'Caution',
    lastChecked: '16:15 IST',
    waypoints: [
      [29.7612, 78.5420],
      [29.7625, 78.5440],
      [29.7640, 78.5460],
    ],
  },
];
